# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD:}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.example.movieapi=DEBUG

spring.security.user.password=

jwt.secret=
jwt.access-expiration=
jwt.refresh-expiration=
